
POST http://127.0.0.1:8000/api/products/
Content-type: application/json


{
  "name": "کفش ورزشی نایک",
  "description": "کفش مخصوص دویدن با کیفیت بالا",
  "price": "150000",
  "stock": 25
}





#POST http://127.0.0.1:8000/api/signup/
# Content-Type: application/json

# {
#    "username": "testuer",
#    "password": "123456"
# }







